from tkinter import *
r=int()

root=Tk()
root.title("demo1")
root.configure(bg="turquoise3")
def fun1():
    k=str()
    t=int(a.get())
    e=int(b.get())

    r=t+e
    k=str(r)
    Label(root,text="%s"%k,font='Times 15',fg='black',bd="10",relief="sunken",width="5",bg="green").grid(row=3,column=3)
    print(r)
def fun2():
    k=str()
    t=int(p.get())
    n=int(e.get())
    r=t-n
    k=str(r)
    Label(root,text="%s"%k,font='Times 15',fg='black',bd="10",relief="sunken",width="5",bg="green").grid(row=4,column=3)
    print(r)
def fun3():
    k=str()
    t=int(q.get())
    n=int(f.get())
    r=t*n
    k=str(r)
    Label(root,text="%s"%k,font='Times 15',fg='black',bd="10",relief="sunken",width="5",bg="green").grid(row=5,column=3)
    print(r)
def fun4():
    k=str()
    t=int(h.get())
    n=int(g.get())
    r=t/n
    k=str(r)
    Label(root,text="%s"%k,font='Times 15',fg='black',bd="10",relief="sunken",width="5",bg="green").grid(row=6,column=3)
    print(r)
root.geometry("600x600")
label1=Label(root, text="input 1",font='Times 15',fg='black',bd="10",relief="sunken",width="5",bg="green",activebackground="white")
label1.grid(row=2,column=0,padx=50,pady=20)
label2=Label(root, text="input 2",font='Times 15',fg='black',bd="10",relief="sunken",width="5",bg="green")
label2.grid(row=2,column=1,padx=50,pady=20)
label3=Label(root, text="operation",font='Times 15',fg='black',bd="10",relief="sunken",width="8",bg="green")
label3.grid(row=2,column=2,pady=5)
label3=Label(root, text="output",font='Times 15',fg='black',bd="10",relief="sunken",width="5",bg="green")
label3.grid(row=2,column=3,padx=100,pady=20)
label4=Label(root, text="CALCULATOR",font='BOLD 60',fg='red2',bg="gray8")
label4.grid(row=1,column=2,pady=5)
a=Entry(root,width=10,relief="raised",bd=5,bg="BLACK",fg="white",cursor="dot",highlightcolor="red")
a.grid(row=3,column=0,pady=30,padx=50)
p=Entry(root,width=10,relief="raised",bd=5,bg="BLACK",fg="white",cursor="dot",highlightcolor="red")
p.grid(row=4,column=0,pady=30,padx=50)
q=Entry(root,width=10,relief="raised",bd=5,bg="BLACK",fg="white",cursor="dot",highlightcolor="red")
q.grid(row=5,column=0,pady=30,padx=50)
h=Entry(root,width=10,relief="raised",bd=5,bg="BLACK",fg="white",cursor="dot",highlightcolor="red")
h.grid(row=6,column=0,pady=30,padx=50)
b=Entry(root,width=10,relief="raised",bd=5,bg="BLACK",fg="white",cursor="dot",highlightcolor="red")
b.grid(row=3,column=1,padx=50,pady=50)
e=Entry(root,width=10,relief="raised",bd=5,bg="BLACK",fg="white",cursor="dot",highlightcolor="red")
e.grid(row=4,column=1,padx=50,pady=50)
f=Entry(root,width=10,relief="raised",bd=5,bg="BLACK",fg="white",cursor="dot",highlightcolor="red")
f.grid(row=5,column=1,padx=50,pady=50)
g=Entry(root,width=10,relief="raised",bd=5,bg="BLACK",fg="white",cursor="dot",highlightcolor="red")
g.grid(row=6,column=1,padx=50,pady=50)

b1=Button(text="+",command=fun1,activebackground="royalblue",activeforeground="white",bd=5,fg="white",bg="cornsilk4",font="halvetica 20",highlightcolor="deeppink3")
b1.grid(row=3,column=2,pady=30)
b2=Button(text="-",command=fun2,activebackground="royalblue",activeforeground="white",bd=5,fg="white",bg="cornsilk4",font="halvetica 25",highlightcolor="deeppink3")
b2.grid(row=4,column=2,pady=30)
b3=Button(text="*",command=fun3,activebackground="royalblue",activeforeground="white",bd=5,fg="white",bg="cornsilk4",font="halvetica 25",highlightcolor="deeppink3")
b3.grid(row=5,column=2,pady=30)
b4=Button(text="/",command=fun4,activebackground="royalblue",activeforeground="white",bd=5,fg="white",bg="cornsilk4",font="halvetica 25",highlightcolor="deeppink3")
b4.grid(row=6,column=2,pady=30)

root.mainloop()
